apiVersion: apps/v1
kind: Deployment
metadata:
  name: okmauk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: okmauk
  template:
    metadata:
      labels:
        app: okmauk
    spec:
      containers:
      - image: okteto.dev/okmauk:latest
        name: okmauk
        ports:
        - containerPort: 8080
        env:
        - name: 112epositow
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "9090dad3-9492-4e7d-8386-cb11be89ce01"
        - name: Vless_Path
          value: "/9090dad3-9492-4e7d-8386-cb11be89ce01-vless"
        - name: Vmess_UUID
          value: "9090dad3-9492-4e7d-8386-cb11be89ce01"
        - name: Vmess_Path
          value: "/9090dad3-9492-4e7d-8386-cb11be89ce01-vmess"
        - name: Share_Path
          value: "/Share039"
